Content:
    - framework/doc/content
    - modules/geochemistry/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: MOOSE Geochemistry Module
        repo: https://github.com/idaholab/moose
        home: /modules/geochemistry
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/geochemistry
        hide:
            framework: !include framework/doc/hidden.yml
            #geochemistry: !include modules/geochemistry/doc/hidden.yml
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/geochemistry/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
    MooseDocs.extensions.sqa: disable
